### PR TITLE
Add Browser Noise Tutorials

### PR DESCRIPTION
**Pull request by meerasndr**

### CODE REVIEW

**Comment by meerasndr** [comment]
Should I add a more generic description relating to the content of the tutorials?

**Comment by notthetup** [comment]
I think this is good enough. https://github.com/sindresorhus/awesome/blob/main/awesome.md has some guidelines on how to list things.

**Comment by notthetup** [comment]
@meerasndr Thanks for all the PRs. Would like to help maintain this awesome list?

**Comment by meerasndr** [comment]
@notthetup I'll be happy to help!

**Pull request merged**
